const main = document.getElementById("main")

const posts = [
    {
        name: "Vincent van Gogh",
        username: "vincey1853",
        location: "Zundert, Netherlands",
        avatar: "images/avatar-vangogh.jpg",
        post: "images/post-vangogh.jpg",
        comment: "Not sure if I'm liking this acid trip.",
        likes: 21492
    },
    {
        name: "Gustave Courbet",
        username: "gus1819",
        location: "Ornans, France",
        avatar: "images/avatar-courbet.jpg",
        post: "images/post-courbet.jpg",
        comment: "OMG I just found some lice in my hair!",
        likes: 12502
    },
        {
        name: "Joseph Ducreux",
        username: "jd1735",
        location: "Paris, France",
        avatar: "images/avatar-ducreux.jpg",
        post: "images/post-ducreux.jpg",
        comment: "Not gonna lie: feeling pretty fine tonight.",
        likes: 15137
    }
]


let loadingEffect = setInterval(generatePosts, 1000) 

//this whole thing work a lot like a manually created "for" loop. The point is just to create a "loading" effect where each post comes in gradually (every 1000 ms, as defined by the setInterval above) and the user can see that it is being generated dynamically by the JavaScript

let i = 0

function generatePosts(){
  
    main.innerHTML += `<div class="overall-post-container" id="post-container${i}">
            <div class="top-info">
                <img class="other-user-avatar" src="${posts[i].avatar}">
                 <div class="top-info-text-element">
                    <p class="other-user-name">${posts[i].name}</p>
                    <p class="other-user-location">${posts[i].location}</p>
                </div> 
            </div> 
            
            <img class="post-image" id="post-image${i}" src="${posts[i].post}"> 
              
            <div class="icon-container">
                <img class="icon" id="heart-icon${i}" src="images/icon-heart.png">
                 <img class="icon" id="comment-icon${i}" src="images/icon-comment.png">
                  <img class="icon dm-icon" src="images/icon-dm.png">
            </div> 
            
            <div class="bottom-info" id="bottom-info${i}">
                <p class="likes"><span id="likes${i}">${posts[i].likes.toLocaleString()}</span> likes</p>
                <p class="comment"><span class="user-name">${posts[i].username}</span> ${posts[i].comment}</p>
            </div> 
            <div class="comment-box" id="comment-box${i}">
                <img class="comment-avatar" src="images/user-avatar.png">
                <div class="input-container" id="input-container${i}">
                    <input class="comment-input" id="comment-input${i}" type="text" placeholder="Add a comment as FakeDaniel77">
                    <button class="comment-button" id="comment-button${i}">Post</button>
                </div> 
            </div>
            </div>`
        
    document.getElementById(`post-container${i}`).style.animation = "fadeInEffect 1s linear" 
    
    window.scrollBy({
        top: window.innerHeight,
        behavior: 'smooth'})            //to scroll down smoothly each time a new post is "loaded"
    

    
    i++
    
    if (i === posts.length) {
        clearInterval(loadingEffect)    //to end the loading effect
    }
} 

// I'm doing some funky things with the event listeners here, the reason being that I can't just add them the normal way, because the html elements don't exist in the DOM until after they're generated by the JavaScript. I'm basically attaching listiners to the entire document and then setting their conditions so that they only activate when the thing I'm targeting (which doesn't exist until the JavaScript generates it) is clicked.  


document.addEventListener("click", function(event){
    if (event.target.id === `comment-icon0`){
        i = 0 
        openCommentBox()
        }
     if (event.target.id === `comment-icon1`){
        i = 1 
         openCommentBox()
        }
      if (event.target.id === `comment-icon2`){
        i = 2 
         openCommentBox()}
    
    function openCommentBox(){
        document.getElementById(`comment-box${i}`).style.display = "flex"}
   
    if (i === 2) {
        window.scrollBy(0, 80)}
    
}) 


document.addEventListener("click", function(event){
    if (event.target.id === `comment-button0`){
        i = 0 
        leaveComment()
        }
    if (event.target.id === `comment-button1`){
        i = 1 
         leaveComment()}
    if (event.target.id === `comment-button2`){
        leaveComment()
        i = 2 }
    
    function leaveComment(){
    if (document.getElementById(`comment-input${i}`).value.trim() === ""){
        document.getElementById(`comment-input${i}`).value = ""
        document.getElementById(`comment-input${i}`).setAttribute("placeholder", "Add a comment as FakeDaniel77")  
    } else {
        let comment = document.getElementById(`comment-input${i}`).value 
        document.getElementById(`bottom-info${i}`).innerHTML += `<p class="comment"><span class="user-name">FakeDaniel77</span> ${comment}</p>`
        document.getElementById(`comment-input${i}`).value  = ""
        document.getElementById(`comment-input${i}`).setAttribute("placeholder", "Add a comment as FakeDaniel77")  
      }
}})    
    

document.addEventListener("click", giveLikeForImage0) 

function giveLikeForImage0(event){
    if (event.target.id === `heart-icon0` || event.target.id === `post-image0`){
        i = 0 
        registerLike()
        changeEventListener0()
        }}
        
        
        
        
document.addEventListener("click", giveLikeForImage1) 

function giveLikeForImage1(event){
    if (event.target.id === `heart-icon1` || event.target.id === `post-image1`){
        i = 1
        registerLike()
        changeEventListener1()
        }}
        
        
        
document.addEventListener("click", giveLikeForImage2) 

function giveLikeForImage2(event){
    if (event.target.id === `heart-icon2` || event.target.id === `post-image2`){
        i = 2
        registerLike()
        changeEventListener2()
        }}
        
        
function registerLike(){
       document.getElementById(`heart-icon${i}`).setAttribute("src", "images/icon-heart-liked.png")
       posts[i].likes++
       document.getElementById(`likes${i}`).textContent = posts[i].likes.toLocaleString()
       }
       

function changeEventListener0(){
       document.removeEventListener("click", giveLikeForImage0)
       document.addEventListener("click", takeAwayLikeForImage0)}

function changeEventListener1(){
       document.removeEventListener("click", giveLikeForImage1)
       document.addEventListener("click", takeAwayLikeForImage1)}

function changeEventListener2(){
       document.removeEventListener("click", giveLikeForImage2)
       document.addEventListener("click", takeAwayLikeForImage2)}
       
       
       
       
function takeAwayLikeForImage0(event){
    if (event.target.id === `heart-icon0` || event.target.id === `post-image0`){
        i = 0 
        registerUnlike()
        changeEventListener0Again()
        }} 

function takeAwayLikeForImage1(event){
    if (event.target.id === `heart-icon1` || event.target.id === `post-image1`){
        i = 1 
        registerUnlike()
        changeEventListener1Again()
        }} 

function takeAwayLikeForImage2(event){
    if (event.target.id === `heart-icon2` || event.target.id === `post-image2`){
        i = 2 
        registerUnlike()
        changeEventListener2Again()
        }} 
        
      
        
function registerUnlike(){
    document.getElementById(`heart-icon${i}`).setAttribute("src", "images/icon-heart.png")
    posts[i].likes--
    document.getElementById(`likes${i}`).textContent = posts[i].likes.toLocaleString()
    document.getElementById(`heart-icon${i}`).id = `heart-icon${i}`
    }

function changeEventListener0Again(){
       document.addEventListener("click", giveLikeForImage0)
       document.removeEventListener("click", takeAwayLikeForImage0)}

function changeEventListener1Again(){
       document.addEventListener("click", giveLikeForImage1)
       document.removeEventListener("click", takeAwayLikeForImage1)}

function changeEventListener2Again(){
       document.addEventListener("click", giveLikeForImage2)
       document.removeEventListener("click", takeAwayLikeForImage2)}
       
       
       

document.addEventListener("click", function(event){
    if (event.target.className === `icon dm-icon`){
        console.log("Hey, come on now... I'm just a module 4 student!")}})
       

        
       




    
    
//         const commentIcon = document.getElementById("comment-icon") 
//         const commentButton = document.getElementById("comment-button") 
//         const commentBox = document.getElementById("comment-box") 
//         const bottom = document.getElementById("bottom-info")
//         const userComment = document.getElementById("comment-input")
//         let commentIconClicked = false
            
//     commentButton.addEventListener("click", function(){
//     if (userComment.value.trim() === ""){
//         userComment.value = ""
//         userComment.setAttribute("placeholder", "No blank comments, buddy!")  
//     } else {
//         bottom.innerHTML += `<p class="comment"><span class="user-name">FakePer3000</span> ${userComment.value}</p>`
//         userComment.value = ""
//         userComment.setAttribute("placeholder", "Add a comment as FakePer3000") }
// })
            
//             }




// commentIcon.addEventListener("click", function(){
//     if (commentIconClicked === false){
//         commentBox.style.display = "flex"
//         commentIconClicked = true}
// })

        
       
    
  
      
    



